on: [workflow_dispatch]
name: Update mirror

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    strategy:
      fail-fast: false
      matrix:
          duckdb_version: [0.5.0]
          python_version:
            - short: '3.6'
            - short: '3.10'
            - short: '3.11'
            - short: '3.12'
              long: '3.12.0-alpha.1'

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version.long || matrix.python_version.short }}
      - run: python${{ matrix.python_version.short }} -m pip install pip wheel oldest-supported-numpy -U
      - run: |
          python${{ matrix.python_version.short }} -m pip wheel duckdb==${{ matrix.duckdb_version }} --wheel-dir wheels --no-binary :all:
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels/*.whl

  upload:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: download

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: download

      - run: pip install python-pypi-mirror

      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            pypi-mirror write-metadata --download-dir download
            pypi-mirror create --download-dir download --mirror-dir mirror
          COMMIT_MESSAGE: "chore: auto update"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-update-${PR_ID}"
          PR_TITLE: "chore: auto update"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
