on: [workflow_dispatch]
name: Update mirror

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: pip install pip wheel git+https://github.com/astrofrog/autowheel -U
      - run: autowheel linux --output-dir wheels
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels/*.whl

  upload:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: download

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: download

      - run: pip install python-pypi-mirror

      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            pypi-mirror write-metadata --download-dir download
            pypi-mirror create --download-dir download --mirror-dir mirror
          COMMIT_MESSAGE: "chore: auto update"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-update-${PR_ID}"
          PR_TITLE: "chore: auto update"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
